markdown: rdiscount
pygments: true
permalink: /:categories/:year/:month/:day/:title.html
auto: true
rdiscount:
  extensions: [smart]
title : 亲爱的罗伊
production_url : http://dearroy.com
description: "做有思想的记录者！"
disqus_shortname: dearroy
author :
  name : DearRoy
  github : dearroy
  twitter : PaulVPSllc
  email: pacer406@qq.com
